config/routes.rb
WishlistBookmarklet::Application.routes.draw do

  get "js/bookmarklet(.:format)" => "js#bookmarklet", :as => :bookmarklet

  get "/add_product" => 'wishlist#add_product', as: :add_product
  
  get '/:user_id' => 'wishlist#show', as: :wishlist

  delete "/product/:id" => 'wishlist#delete_product', as: :delete_product

  devise_for :users

  root to: 'wishlist#show'

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :image, :price, :title, :url, :wishlist_id

  belongs_to :wishlist
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_one :wishlist
  has_many :products, through: :wishlist 

  after_create :create_wishlist

  def create_wishlist
    Wishlist.create(user_id: self.id)
  end
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
  attr_accessible :user_id

  belongs_to :user
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/js_controller.rb
class JsController < ApplicationController
  layout false

  def bookmarklet
  end
end

app/controllers/wishlist_controller.rb
class WishlistController < ApplicationController
  
	before_filter :authenticate_user!, except: :add_product
  
  def show
    @user = current_user
    @products = @user.products
  end

  def add_product      
      
      unless current_user
        respond_to do |format|
          format.js { render partial: '/wishlist/fail.js.erb' }
        end
      else

        wishlist = current_user.wishlist.id
        title = params[:title]
        image = params[:image]
        price = params[:price]
        link_url = params[:link_url]

        @product = Product.create(wishlist_id: wishlist, title: title, image: image, price: price, url: link_url)
        
        if @product.save          
          respond_to do |format|
            format.js
          end
        end
      # else
      #   redirect_to new_user_session_path, error: 'You need to be logged in to use Bookmarklet. Please log in and try again.'
      # end
      end
  end

  def delete_product
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootstrap_flash_helper.rb
module BootstrapFlashHelper
  ALERT_TYPES = [:error, :info, :success, :warning]

  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?
      
      type = :success if type == :notice
      type = :error   if type == :alert
      next unless ALERT_TYPES.include?(type)

      Array(message).each do |msg|
        text = content_tag(:div,
                           content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
                           msg.html_safe, :class => "alert fade in alert-#{type}")
        flash_messages << text if message
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/js_helper.rb
module JsHelper
end

app/helpers/wishlist_helper.rb
module WishlistHelper
end

app/views/js/bookmarklet.js.erb
(function (){

	initMyBookmarklet();
	
	function initMyBookmarklet() {
		(window.myBookmarklet = function() {
			
				function get_amazon_product_info() 
			 	{
			 		var title_span = document.getElementById("btAsinTitle");
			 		var title = title_span.innerText;

			 		var image_tag = document.getElementById("main-image");
			 		var image = image_tag.getAttribute("src");

			 		var price_span = document.getElementById("actualPriceValue");
			 		var price_with_dollar = price_span.innerText;
			 		var price = strip_dollar(price_with_dollar);

			 		var link_url = document.URL;

			 		var product_info = {
			 			title: title,
			 			image: image,
			 			price: price,
			 			link_url: link_url
			 		};
			 		
			 		if (product_info)
				 		{
				 			console.log(product_info);
				 			return product_info;
				 		}
				 	else
				 		{
				 			alert("Something went wrong!");
				 		}
		 		}

			 	function get_etsy_product_info()
			 	{
			 		 	var title_span = document.getElementById("item-title");
				 		var title = title_span.innerText;

				 		var image_div = document.getElementById("fullimage_link1");
				 		var image_tag = image_div.getElementsByTagName("img");
				 		var image = image_tag[0].getAttribute("src");

				 		var price_div = document.getElementsByClassName("item-price");
				 		var price_span = price_div[0].getElementsByClassName("currency-value");
				 		var price = price_span[0].innerText;
				 		
				 		var link_url = document.URL;

						var product_info = {
							title: title,
							image: image,
							price: price,
							link_url: link_url
						};

				 		if (product_info)
				 		{
				 			console.log(product_info);
				 			return product_info;
				 		}
				 		else
				 		{
				 			alert("Something went wrong!");
				 		}
			 	}

			 	function get_jcrew_product_info()
			 	{
			  		var title_span = document.getElementById("pdp-title");
				 		var title = title_span.innerText;

				 		var image_div = document.getElementsByClassName("prod_main_img");
				 		var image_tag = image_div[0].getElementsByTagName("img");
				 		var image = image_tag[0].getAttribute("src");

				 		//should be able to determine which radio button is checked. To improve later.

				 		var price_div = document.getElementsByClassName("pdp-shapes");
					 	var price_span = price_div[0].getElementsByClassName("price");
					 	var price_with_dollar = price_span[0].innerText;
					 	var price = strip_dollar(price_with_dollar);					

				 		var link_url = document.URL;

						var product_info = {
							title: title,
							image: image,
							price: price,
							link_url: link_url
						};
				 		
				 		if (product_info.title = title)
				 		{
				 			return product_info;
				 		}
				 		else
				 		{
				 			console.log("No product_info object");
				 			alert("Something went wrong!");
				 		}
			 	}

			 	function determine_params() 
				{
				 		switch (document.domain) {
					 		case "www.amazon.com":
					 			var amazon = get_amazon_product_info();
					 			return amazon;
					 			break;
					 		case "www.etsy.com":
								var etsy = get_etsy_product_info();
								return etsy;
								break;
					 		case "www.jcrew.com":
					 			var jcrew = get_jcrew_product_info();
					 			return jcrew;
					 			break;
					 		default:
					 			alert("This is not a supported page!");
				 		}
				}	

				function send_data(product_info)
				{
					var domain = 'http://wishlistrapp.herokuapp.com/add_product?';
					var url = domain + "title=" + product_info.title + "&image=" + product_info.image + "&price=" + product_info.price + "&link_url=" + product_info.link_url;
					
					var script = document.createElement('script'); 
					script.setAttribute('language','javascript'); 
					script.setAttribute('src', url); 
					document.body.appendChild(script);
				}

				function strip_dollar(string)
				{
					var stripped = "";
					for ( var i = 0; i < string.length; i++ )
					{
						if (string.charAt(i) != "$")
						{
							stripped += string.charAt(i);
						}
					};
					return stripped
				}

				var product_info = determine_params();
				send_data(product_info);

		})();
	}

})();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Wishlistr" %></title>
    <link href="http://fonts.googleapis.com/css?family=Corben:bold" rel="stylesheet" type="text/css">
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= root_path %>">Wishlistr</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <% if user_signed_in? %>
                <li><%= link_to current_user.email, edit_user_registration_path %></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
                <li><%= link_to "Login", new_user_session_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->
      <!-- <hr/> -->
    </div> <!-- /container -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="span12">
            <% if current_user %>
              <div class="span6" id="about">
                <h3>Wishlistr is a place to store all of your favorite products from around the web.</h3>
              </div>
              <div class="span6" id="bookmarklet-link">
                <a class="bookmarklet btn" href="javascript:(function () { var s = document.createElement('script'); s.setAttribute('language','javascript'); s.setAttribute('src','http://wishlistrapp.herokuapp.com/js/bookmarklet.js'); document.body.appendChild(s);})()">Add to Wishlist</a>
                <p>Drag the button above to your browser toolbar, and click it on any Amazon, Etsy, or JCrew product you want to save.</p>
              </div>
            <% end %>
            <div class="span11">
              <hr/>
            <div id="mgmllr">
              <p>&copy; mgmllr 2013</p>
            </div>
            <div id="nyc">
              <p>Assembled with &lt;3 in NYC.</p>
            </div>
            </div>  
          </div>
        </div>
      </div>
      
     
    </footer>

    

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/wishlist/_fail.js.erb
alert("Something went wrong! Please make sure you're logged into http://wishlistrapp.herokuapp.com/ before using Wishlistr.");

app/views/wishlist/add_product.js.erb
alert("Product successfully added to wishlist!");

app/views/wishlist/delete_product.js.erb
$('#<%= dom_id(@product) %>').fadeOut();

app/views/wishlist/show.html.erb
<%= div_for(@products) do |product| %>
	<div class="product-container">
		<a href="<%= product.url %>">
			<div class="product-header">	
				<h3><%= product.title %></h3>
			</div>
		</a>
		<div class="product-image">
			<img src="<%= product.image %>"/>
		</div>
		<div class="product-footer">
			<p>Price: $<%= product.price %></p>
			<p>Time Saved: <%= time_ago_in_words(product.created_at) %> ago</p>
			<%= button_to 'Delete', delete_product_path(product.id), method: :delete, remote: true %>
		</div>
	</div>	
<% end %>